package com.garveshtiwari.spiritual_app_backend.intelligence.response.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AiResponse {

    /**
     * Final answer generated by the AI.
     */
    private String answer;

    /**
     * Scriptures used while generating the answer.
     */
    private List<Citation> citations;

    /**
     * AI confidence.
     * Phase 5.4
     */
    private Double confidence;

    /**
     * Whether the answer is grounded in retrieved scriptures.
     */
    private Boolean grounded;

    /**
     * Type of AI response.
     */
    private ResponseType responseType;

    /**
     * Suggested follow-up questions.
     */
    private List<String> followUpQuestions;

    /**
     * Related verse ids.
     */
    private List<Long> relatedVerseIds;
}