spring:
  application:
    name: spiritual-app-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/spiritual_app
    username: app_user
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

logging:
  level:
    org.springframework.security: INFO
    root: INFO
    com.garveshtiwari.spiritual_app_backend: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

jwt:
  secret: 123456789012345678901234567890123456789012345678901234567890
  expiration: 86400000

intelligence:
  provider: openai

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-4.1-mini
  base-url: https://api.openai.com